owner: dehunt
repo: upptime-test
sites:
  - name: pdfRest
    url: https://status.pdfrest.com/up
  - name: /bmp
    url: https://status.pdfrest.com/bmp
  - name: /compressed-pdf
    url: https://status.pdfrest.com/compressed-pdf
  - name: /decrypted-pdf
    url: https://status.pdfrest.com/decrypted-pdf
  - name: /encrypted-pdf
    url: https://status.pdfrest.com/encrypted-pdf
  - name: /flattened-annotations-pdf
    url: https://status.pdfrest.com/flattened-annotations-pdf
  - name: /flattened-layers-pdf
    url: https://status.pdfrest.com/flattened-layers-pdf
  - name: /flattened-transparencies-pdf
    url: https://status.pdfrest.com/flattened-transparencies-pdf
  - name: /gif
    url: https://status.pdfrest.com/gif
  - name: /jpg
    url: https://status.pdfrest.com/jpg
  - name: /linearized-pdf
    url: https://status.pdfrest.com/linearized-pdf
  - name: /merged-pdf
    url: https://status.pdfrest.com/merged-pdf
  - name: /pdf
    url: https://status.pdfrest.com/pdf
  - name: /pdf-info
    url: https://status.pdfrest.com/pdf-info
  - name: /pdf-with-added-image
    url: https://status.pdfrest.com/pdf-with-added-image
  - name: /pdfa
    url: https://status.pdfrest.com/pdfa
  - name: /pdfx
    url: https://status.pdfrest.com/pdfx
  - name: /png
    url: https://status.pdfrest.com/png
  - name: /restricted-pdf
    url: https://status.pdfrest.com/restricted-pdf
  - name: /split-pdf
    url: https://status.pdfrest.com/split-pdf
  - name: /tif
    url: https://status.pdfrest.com/tif
  - name: /unrestricted-pdf
    url: https://status.pdfrest.com/unrestricted-pdf
  - name: /upload
    url: https://status.pdfrest.com/upload
  - name: /watermarked-pdf
    url: https://status.pdfrest.com/watermarked-pdf
  - name: /zip
    url: https://status.pdfrest.com/zip
assignees:
  - dehunt
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-test
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Test Status Page
  introTitle: "**Test** open-source uptime monitor and status page."
  introMessage: Status page reporting endpoints
  navbar:
    - title: Status
      href: /
    - title: Test Link
      href: https://google.com
  theme: dark
  # themeUrl: /assets/theme.css
